type=item
items=minecraft:leather_chestplate chainmail_chestplate iron_chestplate golden_chestplate diamond_chestplate netherite_chestplate
nbt.display.Name=ipattern:*space*
model=./space_suit_chestplate