type=armor
items=leather_leggings
texture.leather_layer_2_overlay=optifine/cit/slimefun/9_magical_armor/slime_armor/slime_armor_layer_2
texture.leather_layer_2=optifine/cit/slimefun/9_magical_armor/slime_armor/slime_armor_layer_2
nbt.display.Name=ipattern:Slime Leggings