from=./space_anim.png
to=optifine/cit/slimefun/24_galactifun/equipment/space_suit/space_layer_1.png
x=33
y=20
w=6
h=10
interpolate=true
  tile.0=0
  duration.0=15
  tile.1=1
  duration.1=15
  tile.0=0
  duration.1=5
  tile.1=1
  duration.1=10