name: DyedBackpacks
version: ${project.version}
author: TheBusyBiscuit

description: A Slimefun Addon that adds dyed backpacks
website: https://github.com/TheBusyBiscuit/DyedBackpacks

main: com.github.drakescraft_labs.dyedbackpacks.DyedBackpacks
depend: [Slimefun]

api-version: "1.21"
