type=item
items=minecraft:chainmail_chestplate iron_chestplate golden_chestplate diamond_chestplate netherite_chestplate
nbt.display.Name=ipattern:*Jackstar*|*jackstar*|*DrakesCraft*|*drakecraft*|*Racingsky*|*racingsky*