type=armor
items=leather_leggings
texture.leather_layer_2_overlay=optifine/cit/slimefun/12_armor/hazmat_suit_armor/hazmat_suit_layer_2
texture.leather_layer_2=optifine/cit/slimefun/12_armor/hazmat_suit_armor/hazmat_suit_layer_2
nbt.display.Name=ipattern:Hazmat Suit Leggings