type=armor
items=leather_helmet
texture.leather_layer_1_overlay=optifine/cit/slimefun/12_armor/hazmat_suit_armor/hazmat_suit_layer_1
texture.leather_layer_1=optifine/cit/slimefun/12_armor/hazmat_suit_armor/hazmat_suit_layer_1
nbt.display.Name=ipattern:Scuba Helmet