name: SFCalc
main: com.github.drakescraft_labs.sfcalc.SFCalc
version: 1.21-Drake-v1
author: Seggan
depend: [Slimefun]
api-version: 1.15

commands:
  sfcalc:
    description: Base SFCalc command
    usage: "Usage: /sfcalc calc <item> [amount]"
    aliases:
      - sfc
