name: SlimeChem
authors: [Mooy1, Seggan, TheBusyBiscuit]
description: slimefun chemistry
main: com.github.drakescraft_labs.slimechem.SlimeChem
depend: [Slimefun]
version: 1.21-Drake-v7
api-version: "1.21"
