type=item
items=minecraft:bow
nbt.display.Name=ipattern:Acri Arcum
model.bow_standby=./acri_arcum_bow_standby
model.bow_pulling_0=./acri_arcum_bow_pulling_0
model.bow_pulling_1=./acri_arcum_bow_pulling_1
model.bow_pulling_2=./acri_arcum_bow_pulling_2