type=item
items=minecraft:bow
nbt.display.Name=ipattern:Healing Bow
model.bow_standby=./healing_bow_standby
model.bow_pulling_0=./healing_bow_pulling_0
model.bow_pulling_1=./healing_bow_pulling_1
model.bow_pulling_2=./healing_bow_pulling_2