name: TemplateAddon
version: 1.21.11-Drake
main: dev.drake.template.TemplateAddon
api-version: "1.21"
authors:
  - drakescraft_labs
depend:
  - Slimefun
description: Plantilla base para addons nuevos sobre Slimefun 6 / Drake Framework.
