type=armor
items=leather_leggings
texture.leather_layer_2_overlay=optifine/cit/slimefun/6_extragear/copper/armor_set/copper_layer_2
texture.leather_layer_2=optifine/cit/slimefun/6_extragear/copper/armor_set/copper_layer_2
nbt.display.Name=ipattern:Copper Leggings