name: ColoredEnderChests
version: ${project.version}
author: TheBusyBiscuit
website: https://github.com/TheBusyBiscuit/ColoredEnderChests

main: com.github.drakescraft_labs.coloredenderchests.ColoredEnderChests
api-version: 1.13

depend: 
- Slimefun
