from=./fiery_leggings_layer_2_anim.png
to=optifine/cit/slimefun/27_foxy_machines/weapons_and_armor/fiery_leggings_armor/fiery_leggings_layer_2.png
x=0
y=16
w=16
h=14
interpolate=true
  tile.0=0
  tile.1=1
  tile.2=2
  tile.3=3

  duration.3=6
  duration.2=6
  duration.1=6
  duration.0=6
  duration.1=6
  duration.2=6