type=armor
items=netherite_helmet
texture.netherite_layer_1=optifine/cit/slimefun/27_foxy_machines/weapons_and_armor/aquatic_helmet_armor/aquatic_helmet_layer_1
nbt.display.Name=ipattern:Aquatic Helmet