type=armor
items=netherite_leggings
texture.netherite_layer_2=optifine/cit/slimefun/27_foxy_machines/weapons_and_armor/fiery_leggings_armor/fiery_leggings_layer_2
nbt.display.Name=ipattern:Fiery Leggings