type=armor
items=netherite_chestplate
texture.netherite_layer_1=optifine/cit/slimefun/27_foxy_machines/weapons_and_armor/resistant_chestplate_armor/resistant_chestplate_layer_1
nbt.display.Name=ipattern:Resistant Chestplate