type=item
items=minecraft:bow
model.bow_standby=./explosive_bow_standby
model.bow_pulling_0=./explosive_bow_pulling_0
model.bow_pulling_1=./explosive_bow_pulling_1
model.bow_pulling_2=./explosive_bow_pulling_2
nbt.display.Name=ipattern:Explosive Bow