type=item
items=minecraft:bow
model.bow_standby=./soulbound_bow_standby
model.bow_pulling_0=./soulbound_bow_pulling_0
model.bow_pulling_1=./soulbound_bow_pulling_1
model.bow_pulling_2=./soulbound_bow_pulling_2
nbt.display.Name=ipattern:Soulbound Bow