type=item
items=minecraft:bow
model.bow_standby=./og_bow_standby
model.bow_pulling_0=./og_bow_pulling_0
model.bow_pulling_1=./og_bow_pulling_1
model.bow_pulling_2=./og_bow_pulling_2
nbt.display.Name=ipattern:*OG*