name: NetworksV6-Drake
authors: [Sefiraat, Chagui68, DrakesCraft-Labs]
description: Networks V6 ported and stabilized for Drake Labs 1.21.x.
main: io.github.sefiraat.networks.Networks
website: https://github.com/DrakesCraft-Labs/drakes-slimefun-labs
version: ${project.version}
api-version: "1.21"
depend:
  - Slimefun
softdepend:
  - InfinityExpansion
  - Netheopoiesis
  - InfinityExpansion2
  - Supreme
  - Cultivation
  - GeneticChickengineering
  - DynaTech
  - SlimyTreeTaps
  - ElectricSpawners
  - ExtraTools
  - TranscEndence
  - FluffyMachines
  - FoxyMachines
  - GlobalWarming
  - SlimefunWarfare
  - Liquid
  - AlchimiaVitae
  - FNAmplifications
  - ElementManipulation
  - SlimeHUD
  - WildChests
  - WeaponsAddon
commands:
  networks:
    description: /networks
    usage: /networks <sub>
