name: "Gate: Standard Addons"

on:
  # push:
    # branches: [1.21-latin]
  workflow_dispatch:

concurrency:
  group: gate-standard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: github
          settings-path: ${{ github.workspace }}
      
      - name: Build Standard Addons
        run: mvn -B clean deploy -DskipTests -pl sources/repos-to-port/ColoredEnderChests,sources/repos-to-port/DyedBackpacks,sources/repos-to-port/DynaTech,sources/repos-to-port/EcoPower,sources/repos-to-port/ElectricSpawners,sources/repos-to-port/ExoticGarden,sources/repos-to-port/ExtraGear,sources/repos-to-port/ExtraHeads,sources/repos-to-port/ExtraUtils,sources/repos-to-port/FluffyMachines,sources/repos-to-port/GlobalWarming,sources/repos-to-port/HardcoreSlimefun,sources/repos-to-port/HotbarPets,sources/repos-to-port/InfinityExpansion,sources/repos-to-port/luckyblocks-sf,sources/repos-to-port/MobCapturer,sources/repos-to-port/PrivateStorage,sources/repos-to-port/SFCalc,sources/repos-to-port/SFMobDrops,sources/repos-to-port/SimpleUtils,sources/repos-to-port/SlimeChem,sources/repos-to-port/SlimefunOreChunks,sources/repos-to-port/SlimyRepair,sources/repos-to-port/SlimyTreeTaps,sources/repos-to-port/SoulJars,sources/repos-to-port/SoundMuffler -am -s ${{ github.workspace }}/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
