name: "Gate: Community Addons"

on:
  push:
    branches: [1.21-latin]
  workflow_dispatch:

concurrency:
  group: gate-community-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: github
          settings-path: ${{ github.workspace }}
      
      - name: Build Community Addons
        run: mvn -B clean deploy -DskipTests -pl sources/community-addons/AlchimiaVitae,sources/community-addons/CrystamaeHistoria,sources/community-addons/DankTech2,sources/community-addons/DyeBench,sources/community-addons/Element-Manipulation,sources/community-addons/ExtraTools,sources/community-addons/FlowerPower,sources/community-addons/FN-FAL-s-Amplifications,sources/community-addons/FoxyMachines,sources/community-addons/GeneticChickengineering-Reborn,sources/community-addons/HeadLimiter,sources/community-addons/Liquid,sources/community-addons/Magic-8-Ball,sources/community-addons/MapJammers,sources/community-addons/MissileWarfare,sources/community-addons/MiniBlocks,sources/community-addons/PotionExpansion,sources/community-addons/RykenSlimeCustomizer-EN,sources/community-addons/SfChunkInfo,sources/community-addons/Simple-Storage,sources/community-addons/SlimeCustomizer,sources/community-addons/UltimateGenerators2,sources/community-addons/VillagerUtil -am -s ${{ github.workspace }}/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
